version: 2

jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:16.04
      - image: python:3.5
    parallelism: 1
    environment:
      DISTRIB: "conda"
      PYTHON_VERSION: "3.5"
      NUMPY_VERSION: "1.17.3"
      SCIPY_VERSION: "*"
      SCIKIT_LEARN_VERSION: "*"
      MATPLOTLIB_VERSION: "*"
      NIPYPE_VERSION: "0.13.0"

    steps:
      - checkout
      - restore_cache:
          key: spm12+datasets+pypi-{{ .Branch }}
      - run: wget https://repo.continuum.io/miniconda/Miniconda3-4.6.14-Linux-x86_64.sh -O ~/miniconda.sh
      - run: chmod +x ~/miniconda.sh && ~/miniconda.sh -b
      - run: echo 'export PATH="$HOME/miniconda3/bin:$PATH"'  >> $BASH_ENV
      - run:
          name: Create conda env
          command: |
            conda create -n testenv python=3.5 numpy=1.17.3 -yq
      #- run: sudo apt-get update
      #- run: sudo apt-get install libxm4 libxpm4 libxmu6 libxt6 bc
      - run:
          name: Installing SPM & exporting its paths + other path
          command: |
            source activate testenv
            source continuous_integration/setup_spm.sh
            echo 'export SPM_ROOT_DIR="$HOME/opt/spm12"' >> $BASH_ENV
            echo 'export SPM_DIR="$SPM_ROOT_DIR/spm12/"' >> $BASH_ENV
            echo 'export SPM_MCR="$SPM_ROOT_DIR/spm12.sh"' >> $BASH_ENV
            echo 'export PATH="/home/circleci/.local/bin:$PATH"' >> $BASH_ENV
            pip install --upgrade pip
            pip install scipy sklearn nibabel configobj nose coverage pytest -q
            pip install matplotlib pandas nipype nilearn -q
            python setup.py install --user
            python -c "from pypreprocess import datasets; datasets.fetch_spm_auditory(); datasets.fetch_spm_multimodal_fmri(); datasets.fetch_fsl_feeds()"
            make clean
            make test-code
            cd examples/easy_start && python nipype_preproc_spm_auditory.py
      #- run: cd examples/pipelining && python nipype_preproc_spm_multimodal_faces.py
      #- run: cd examples/pipelining && python nistats_glm_fsl_feeds_fmri.py
      #- run: sh continuous_integration/clean_output.sh
      - save_cache:
          key: spm12+datasets+pypi-{{ .Branch }}
          paths:
            - $SPM_ROOT_DIR
            - $HOME/nilearn_data
            - $HOME/.local/bin

      #- store_artifacts:
      #    path: $HOME/nilearn_data/spm_auditory/pypreprocess_output/
      #- store_artifacts:
      #    path: $HOME/nilearn_data/spm_multimodal_fmri/pypreprocess_output/
      #- store_artifacts:
      #    path: $HOME/nilearn_data/fsl_feeds/pypreprocess_output/
